#ifndef __COMMANDERKERNAEL_KEYBOARD_LANGUAGES_LANGUAGES_HPP
#define __COMMANDERKERNAEL_KEYBOARD_LANGUAGES_LANGUAGES_HPP

#include <Headers/keyboards/italian.hpp>
#include <Headers/keyboards/english.hpp>

#endif //__COMMANDERKERNAEL_KEYBOARD_LANGUAGES_LANGUAGES_HPP
